function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-Jul-2020 17:03:16

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'LineWidth',1.5,'LineStyle','--','Color',[0 0 0]);
set(plot1(2),'LineWidth',2,'Color',[0 0.447058823529412 0.741176470588235]);

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 4]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12,'FontWeight','bold','GridAlpha',0.1,'LineWidth',1.5,...
    'XGrid','on','YGrid','on');
