function plot_shluk(X1, YMatrix1) % napø.  plot_shluk(y,[gg ; hh ; kk])
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-Jul-2020 09:43:00

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'Color',[1 0 0]);
set(plot1(2),'Color',[0.074509803921569 0.623529411764706 1]);
set(plot1(3),...
    'Color',[0.929411764705882 0.694117647058824 0.125490196078431]);

% Create ylabel
ylabel('r(x)');

% Create xlabel
xlabel('x');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 3.5]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 3.5]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12,'FontWeight','bold','GridAlpha',0.1,'LineWidth',1.5,...
    'XGrid','on','YGrid','on');
