% plots the 'rigidity function'
function rigidita(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-Jul-2020 16:30:00

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1);
set(plot1(1),'LineWidth',1.5,'LineStyle','--','Color',[0 0 0]);
set(plot1(2),'LineWidth',2,'Color',[1 0 0]);
set(plot1(3),'LineWidth',1.5,'LineStyle','--','Color',[0 0 0]);
set(plot1(4),'LineWidth',2,'Color',[0 0.447058823529412 0.741176470588235]);
set(plot1(5),'LineWidth',1.5,'LineStyle','--','Color',[0 0 0]);
set(plot1(6),'LineWidth',2,...
    'Color',[0.929411764705882 0.694117647058824 0.125490196078431]);

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 1.5]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0 1.5]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12,'FontWeight','bold','GridAlpha',0.1,'LineWidth',1.5,...
    'XGrid','on','XTick',[0 0.25 0.5 0.75 1 1.25 1.5],'YGrid','on','YTick',...
    [0 0.25 0.5 0.75 1 1.25 1.5]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.213342883990454 0.60198413507333 0.133433281660437 0.28690475381556]);

