function createhist(data1)
%CREATEFIGURE1(data1)
%  DATA1:  histogram data

%  Auto-generated by MATLAB on 03-Jul-2020 11:07:29

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create histogram
histogram(data1,'Parent',axes1,'FaceAlpha',0.8,...
    'FaceColor',[0.392156862745098 0.831372549019608 0.074509803921569],...
    'Normalization','pdf',...
    'BinEdges',[0,0.150000000000000,0.300000000000000,0.450000000000000,0.600000000000000,0.700000000000000,0.850000000000000,1,1.15000000000000,1.30000000000000,1.30000000000000,1.50000000000000,1.70000000000000,1.90000000000000,2.10000000000000,2.30000000000000,2.50000000000000,2.50000000000000,2.80000000000000,2.80000000000000,3.40000000000000,3.40000000000000,4,4.60000000000000,5.20000000000000,5.80000000000000,6.40000000000000,7.00000000000000,7.60000000000000,8.20000000000000]);

% Create xlabel
xlabel('Škálovaná èasová svìtlost (s)');
ylabel('Hustota pravdìpodobnosti (1/s)');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 5]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12,'FontWeight','bold','LineWidth',1.5);
